shop:
  title: '&8&lCRATE SMP &5Shop'
  size: 54
  items:
    iron:
      material: IRON_INGOT
      name: '&fIron Ingot'
      price: 1500
      sell-price: 375
      slot: 10
    gold:
      material: GOLD_INGOT
      name: '&6Gold Ingot'
      price: 2500
      sell-price: 625
      slot: 11
    emerald:
      material: EMERALD
      name: '&aEmerald'
      price: 3500
      sell-price: 875
      slot: 12
    diamond:
      material: DIAMOND
      name: '&bDiamond'
      price: 4500
      sell-price: 1125
      slot: 13
    netherite:
      material: NETHERITE_INGOT
      name: '&5Netherite Ingot'
      price: 200000
      sell-price: 50000
      slot: 14
